### ISSUE TITLE
服务器异常

### ISSUE THREAD

**Issue by bill-bil** [JRY1009/lighthouse_flutter#1]
服务器 异常，看不到数据

**Comment by JRY1009** [comment]
> 服务器 异常，看不到数据

部分接口因为没做跨域配置暂时无法用web访问，可以在Android或iOS环境上看效果

**Comment by bill-bil** [comment]
Android上运行报错
![image](https://user-images.githubusercontent.com/74221254/129540514-84433e2a-5d2a-4056-8496-8df944dc7c89.png)

**Comment by JRY1009** [comment]
close
